# Name of the project
PROJECT_NAME = STUDENT_MANAGEMENT_SYSTEM

#Doxyfile folder
DOC = documentation

#All source code files
SRC = student.c\
src/student_operations.c

#All test source files
TEST_SRC = src/student_operations.c\
test/test_student_operations.c\
unity/unity.c

TEST_OUTPUT = Test_a.out

#All include folders with header files
INC = -Iinc\
-Iunity\

#Project Output Name
PROJECT_OUTPUT = student.out

#Document files
DOCUMENTATION_OUTPUT = documentation/html
Build:
	gcc function1.c test_student.c unity/unity.c -Iunity
Run:
	./a.out